### ISSUE TITLE
second tab shows already done tasks

### ISSUE THREAD

**Issue by MaDill** [dmfs/tasks#158]
On the second tab, German "Aufgaben fällig", it shows me task, which are already done. This tasks are also in the wrong category. For example in the today group, German "Heute fällig", it shows me tasks from some days ago and some weeks ago.
I use the latest version from Google play store together with DavDroid.

**Comment by MaDill** [comment]
That tasks, which are already done shown up, I found the check mark to hide them. But why I see on the today menu tasks from several days ago and are shown with due today?

**Comment by dmfs** [comment]
There is a feature request for this #85
Initially the idea was to show overdue tasks in "today", because it's assumed that they should be completed as soon as possible (since they should have been completed already).
We've assumed that one of the following three things should happen when a task is due:

* ideally the task gets completed
* the due date is moved to a later date
* the task doesn't need to be completed and gets cancelled

We didn't expect that users keep overdue tasks floating around.

I'm closing this, because it kind of duplicates #85
